/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_givimad_whisperjni_WhisperJNI */

#ifndef _Included_io_github_givimad_whisperjni_WhisperJNI
#define _Included_io_github_givimad_whisperjni_WhisperJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_givimad_whisperjni_WhisperJNI
 * Method:    init
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_github_givimad_whisperjni_WhisperJNI_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_github_givimad_whisperjni_WhisperJNI
 * Method:    initNoState
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_github_givimad_whisperjni_WhisperJNI_initNoState
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_github_givimad_whisperjni_WhisperJNI
 * Method:    initState
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_io_github_givimad_whisperjni_WhisperJNI_initState
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_github_givimad_whisperjni_WhisperJNI
 * Method:    isMultilingual
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_givimad_whisperjni_WhisperJNI_isMultilingual
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_github_givimad_whisperjni_WhisperJNI
 * Method:    full
 * Signature: (ILio/github/givimad/whisperjni/WhisperFullParams;[FI)I
 */
JNIEXPORT jint JNICALL Java_io_github_givimad_whisperjni_WhisperJNI_full
  (JNIEnv *, jobject, jint, jobject, jfloatArray, jint);

/*
 * Class:     io_github_givimad_whisperjni_WhisperJNI
 * Method:    fullWithState
 * Signature: (IILio/github/givimad/whisperjni/WhisperFullParams;[FI)I
 */
JNIEXPORT jint JNICALL Java_io_github_givimad_whisperjni_WhisperJNI_fullWithState
  (JNIEnv *, jobject, jint, jint, jobject, jfloatArray, jint);

/*
 * Class:     io_github_givimad_whisperjni_WhisperJNI
 * Method:    fullNSegments
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_io_github_givimad_whisperjni_WhisperJNI_fullNSegments
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_github_givimad_whisperjni_WhisperJNI
 * Method:    fullNSegmentsFromState
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_io_github_givimad_whisperjni_WhisperJNI_fullNSegmentsFromState
  (JNIEnv *, jobject, jint);



/*
 * Class:     io_github_givimad_whisperjni_WhisperJNI
 * Method:    fullGetSegmentTimestamp0
 * Signature: (II)J;
 */
JNIEXPORT jlong JNICALL Java_io_github_givimad_whisperjni_WhisperJNI_fullGetSegmentTimestamp0
  (JNIEnv *, jobject, jint, jint);



/*
 * Class:     io_github_givimad_whisperjni_WhisperJNI
 * Method:    fullGetSegmentTimestamp1
 * Signature: (II)J;
 */
JNIEXPORT jlong JNICALL Java_io_github_givimad_whisperjni_WhisperJNI_fullGetSegmentTimestamp1
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     io_github_givimad_whisperjni_WhisperJNI
 * Method:    fullGetSegmentText
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_givimad_whisperjni_WhisperJNI_fullGetSegmentText
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     io_github_givimad_whisperjni_WhisperJNI
 * Method:    fullGetSegmentTimestamp0FromState
 * Signature: (II)J;
 */
JNIEXPORT jlong JNICALL Java_io_github_givimad_whisperjni_WhisperJNI_fullGetSegmentTimestamp0FromState
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     io_github_givimad_whisperjni_WhisperJNI
 * Method:    fullGetSegmentTimestamp1FromState
 * Signature: (II)J;
 */
JNIEXPORT jlong JNICALL Java_io_github_givimad_whisperjni_WhisperJNI_fullGetSegmentTimestamp1FromState
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     io_github_givimad_whisperjni_WhisperJNI
 * Method:    fullGetSegmentTextFromState
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_givimad_whisperjni_WhisperJNI_fullGetSegmentTextFromState
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     io_github_givimad_whisperjni_WhisperJNI
 * Method:    freeContext
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_github_givimad_whisperjni_WhisperJNI_freeContext
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_github_givimad_whisperjni_WhisperJNI
 * Method:    freeState
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_github_givimad_whisperjni_WhisperJNI_freeState
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
